// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI4ozAgrIU4WY-fTYvb2Jga4Doi5DLeX0',
    appId: '1:754609968387:web:64093e64a2d816492b4536',
    messagingSenderId: '754609968387',
    projectId: 'eventecflutter',
    authDomain: 'eventecflutter.firebaseapp.com',
    storageBucket: 'eventecflutter.appspot.com',
    measurementId: 'G-N0V9FPYZNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexJcoeqVNHVSk82TMmoIL_KA-t542fr4',
    appId: '1:754609968387:android:49e7eb412af6c95a2b4536',
    messagingSenderId: '754609968387',
    projectId: 'eventecflutter',
    storageBucket: 'eventecflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYERtqRlWDAWLJS-8yWKOMndzcH6H0_PY',
    appId: '1:754609968387:ios:548a6346f1ce261d2b4536',
    messagingSenderId: '754609968387',
    projectId: 'eventecflutter',
    storageBucket: 'eventecflutter.appspot.com',
    iosClientId: '754609968387-21vg2ntc9cngoictqhehhjtifu8rmipe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYERtqRlWDAWLJS-8yWKOMndzcH6H0_PY',
    appId: '1:754609968387:ios:548a6346f1ce261d2b4536',
    messagingSenderId: '754609968387',
    projectId: 'eventecflutter',
    storageBucket: 'eventecflutter.appspot.com',
    iosClientId: '754609968387-21vg2ntc9cngoictqhehhjtifu8rmipe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI4ozAgrIU4WY-fTYvb2Jga4Doi5DLeX0',
    appId: '1:754609968387:web:7e528862c08ff13f2b4536',
    messagingSenderId: '754609968387',
    projectId: 'eventecflutter',
    authDomain: 'eventecflutter.firebaseapp.com',
    storageBucket: 'eventecflutter.appspot.com',
    measurementId: 'G-1SXN2WZF50',
  );
}
